const radixColors = require("@radix-ui/colors");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: ({ colors }) => ({
      transparent: colors.transparent,
    }),
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)"],
      },
    },
  },
  plugins: [
    require("windy-radix-palette")({
      colors: {
        slate: radixColors.slate,
        gray: {
          gray1: "var(--slate1)",
          gray2: "var(--slate2)",
          gray3: "var(--slate3)",
          gray4: "var(--slate4)",
          gray5: "var(--slate5)",
          gray6: "var(--slate6)",
          gray7: "var(--slate7)",
          gray8: "var(--slate8)",
          gray9: "var(--slate9)",
          gray10: "var(--slate10)",
          gray11: "var(--slate11)",
          gray12: "var(--slate12)",
        },

        slateDark: radixColors.slateDark,
        grayDark: {
          grayDark1: "var(--slateDark1)",
          grayDark2: "var(--slateDark2)",
          grayDark3: "var(--slateDark3)",
          grayDark4: "var(--slateDark4)",
          grayDark5: "var(--slateDark5)",
          grayDark6: "var(--slateDark6)",
          grayDark7: "var(--slateDark7)",
          grayDark8: "var(--slateDark8)",
          grayDark9: "var(--slateDark9)",
          grayDark10: "var(--slateDark10)",
          grayDark11: "var(--slateDark11)",
          grayDark12: "var(--slateDark12)",
        },

        indigo: radixColors.indigo,
        accent: {
          accent1: "var(--indigo1)",
          accent2: "var(--indigo2)",
          accent3: "var(--indigo3)",
          accent4: "var(--indigo4)",
          accent5: "var(--indigo5)",
          accent6: "var(--indigo6)",
          accent7: "var(--indigo7)",
          accent8: "var(--indigo8)",
          accent9: "var(--indigo9)",
          accent10: "var(--indigo10)",
          accent11: "var(--indigo11)",
          accent12: "var(--indigo12)",
        },

        indigoA: radixColors.indigoA,
        accentA: {
          accentA1: "var(--indigoA1)",
          accentA2: "var(--indigoA2)",
          accentA3: "var(--indigoA3)",
          accentA4: "var(--indigoA4)",
          accentA5: "var(--indigoA5)",
          accentA6: "var(--indigoA6)",
          accentA7: "var(--indigoA7)",
          accentA8: "var(--indigoA8)",
          accentA9: "var(--indigoA9)",
          accentA10: "var(--indigoA10)",
          accentA11: "var(--indigoA11)",
          accentA12: "var(--indigoA12)",
        },

        indigoDark: radixColors.indigoDark,
        accentDark: {
          accentDark1: "var(--indigoDark1)",
          accentDark2: "var(--indigoDark2)",
          accentDark3: "var(--indigoDark3)",
          accentDark4: "var(--indigoDark4)",
          accentDark5: "var(--indigoDark5)",
          accentDark6: "var(--indigoDark6)",
          accentDark7: "var(--indigoDark7)",
          accentDark8: "var(--indigoDark8)",
          accentDark9: "var(--indigoDark9)",
          accentDark10: "var(--indigoDark10)",
          accentDark11: "var(--indigoDark11)",
          accentDark12: "var(--indigoDark12)",
        },

        indigoDarkA: radixColors.indigoDarkA,
        accentDarkA: {
          accentDarkA1: "var(--indigoDarkA1)",
          accentDarkA2: "var(--indigoDarkA2)",
          accentDarkA3: "var(--indigoDarkA3)",
          accentDarkA4: "var(--indigoDarkA4)",
          accentDarkA5: "var(--indigoDarkA5)",
          accentDarkA6: "var(--indigoDarkA6)",
          accentDarkA7: "var(--indigoDarkA7)",
          accentDarkA8: "var(--indigoDarkA8)",
          accentDarkA9: "var(--indigoDarkA9)",
          accentDarkA10: "var(--indigoDarkA10)",
          accentDarkA11: "var(--indigoDarkA11)",
          accentDarkA12: "var(--indigoDarkA12)",
        },

        red: radixColors.red,
        error: {
          error1: "var(--red1)",
          error2: "var(--red2)",
          error3: "var(--red3)",
          error4: "var(--red4)",
          error5: "var(--red5)",
          error6: "var(--red6)",
          error7: "var(--red7)",
          error8: "var(--red8)",
          error9: "var(--red9)",
          error10: "var(--red10)",
          error11: "var(--red11)",
          error12: "var(--red12)",
        },

        redA: radixColors.redA,
        errorA: {
          errorA1: "var(--redA1)",
          errorA2: "var(--redA2)",
          errorA3: "var(--redA3)",
          errorA4: "var(--redA4)",
          errorA5: "var(--redA5)",
          errorA6: "var(--redA6)",
          errorA7: "var(--redA7)",
          errorA8: "var(--redA8)",
          errorA9: "var(--redA9)",
          errorA10: "var(--redA10)",
          errorA11: "var(--redA11)",
          errorA12: "var(--redA12)",
        },

        redDark: radixColors.redDark,
        errorDark: {
          errorDark1: "var(--redDark1)",
          errorDark2: "var(--redDark2)",
          errorDark3: "var(--redDark3)",
          errorDark4: "var(--redDark4)",
          errorDark5: "var(--redDark5)",
          errorDark6: "var(--redDark6)",
          errorDark7: "var(--redDark7)",
          errorDark8: "var(--redDark8)",
          errorDark9: "var(--redDark9)",
          errorDark10: "var(--redDark10)",
          errorDark11: "var(--redDark11)",
          errorDark12: "var(--redDark12)",
        },

        redDarkA: radixColors.redDarkA,
        errorDarkA: {
          errorDarkA1: "var(--redDarkA1)",
          errorDarkA2: "var(--redDarkA2)",
          errorDarkA3: "var(--redDarkA3)",
          errorDarkA4: "var(--redDarkA4)",
          errorDarkA5: "var(--redDarkA5)",
          errorDarkA6: "var(--redDarkA6)",
          errorDarkA7: "var(--redDarkA7)",
          errorDarkA8: "var(--redDarkA8)",
          errorDarkA9: "var(--redDarkA9)",
          errorDarkA10: "var(--redDarkA10)",
          errorDarkA11: "var(--redDarkA11)",
          errorDarkA12: "var(--redDarkA12)",
        },

        grass: radixColors.grass,
        success: {
          success1: "var(--grass1)",
          success2: "var(--grass2)",
          success3: "var(--grass3)",
          success4: "var(--grass4)",
          success5: "var(--grass5)",
          success6: "var(--grass6)",
          success7: "var(--grass7)",
          success8: "var(--grass8)",
          success9: "var(--grass9)",
          success10: "var(--grass10)",
          success11: "var(--grass11)",
          success12: "var(--grass12)",
        },

        grassA: radixColors.grassA,
        successA: {
          successA1: "var(--grassA1)",
          successA2: "var(--grassA2)",
          successA3: "var(--grassA3)",
          successA4: "var(--grassA4)",
          successA5: "var(--grassA5)",
          successA6: "var(--grassA6)",
          successA7: "var(--grassA7)",
          successA8: "var(--grassA8)",
          successA9: "var(--grassA9)",
          successA10: "var(--grassA10)",
          successA11: "var(--grassA11)",
          successA12: "var(--grassA12)",
        },

        grassDark: radixColors.grassDark,
        successDark: {
          successDark1: "var(--grassDark1)",
          successDark2: "var(--grassDark2)",
          successDark3: "var(--grassDark3)",
          successDark4: "var(--grassDark4)",
          successDark5: "var(--grassDark5)",
          successDark6: "var(--grassDark6)",
          successDark7: "var(--grassDark7)",
          successDark8: "var(--grassDark8)",
          successDark9: "var(--grassDark9)",
          successDark10: "var(--grassDark10)",
          successDark11: "var(--grassDark11)",
          successDark12: "var(--grassDark12)",
        },

        grassDarkA: radixColors.grassDarkA,
        successDarkA: {
          successDarkA1: "var(--grassDarkA1)",
          successDarkA2: "var(--grassDarkA2)",
          successDarkA3: "var(--grassDarkA3)",
          successDarkA4: "var(--grassDarkA4)",
          successDarkA5: "var(--grassDarkA5)",
          successDarkA6: "var(--grassDarkA6)",
          successDarkA7: "var(--grassDarkA7)",
          successDarkA8: "var(--grassDarkA8)",
          successDarkA9: "var(--grassDarkA9)",
          successDarkA10: "var(--grassDarkA10)",
          successDarkA11: "var(--grassDarkA11)",
          successDarkA12: "var(--grassDarkA12)",
        },

        yellow: radixColors.yellow,
        warning: {
          warning1: "var(--yellow1)",
          warning2: "var(--yellow2)",
          warning3: "var(--yellow3)",
          warning4: "var(--yellow4)",
          warning5: "var(--yellow5)",
          warning6: "var(--yellow6)",
          warning7: "var(--yellow7)",
          warning8: "var(--yellow8)",
          warning9: "var(--yellow9)",
          warning10: "var(--yellow10)",
          warning11: "var(--yellow11)",
          warning12: "var(--yellow12)",
        },

        yellowA: radixColors.yellowA,
        warningA: {
          warningA1: "var(--yellowA1)",
          warningA2: "var(--yellowA2)",
          warningA3: "var(--yellowA3)",
          warningA4: "var(--yellowA4)",
          warningA5: "var(--yellowA5)",
          warningA6: "var(--yellowA6)",
          warningA7: "var(--yellowA7)",
          warningA8: "var(--yellowA8)",
          warningA9: "var(--yellowA9)",
          warningA10: "var(--yellowA10)",
          warningA11: "var(--yellowA11)",
          warningA12: "var(--yellowA12)",
        },

        yellowDark: radixColors.yellowDark,
        warningDark: {
          warningDark1: "var(--yellowDark1)",
          warningDark2: "var(--yellowDark2)",
          warningDark3: "var(--yellowDark3)",
          warningDark4: "var(--yellowDark4)",
          warningDark5: "var(--yellowDark5)",
          warningDark6: "var(--yellowDark6)",
          warningDark7: "var(--yellowDark7)",
          warningDark8: "var(--yellowDark8)",
          warningDark9: "var(--yellowDark9)",
          warningDark10: "var(--yellowDark10)",
          warningDark11: "var(--yellowDark11)",
          warningDark12: "var(--yellowDark12)",
        },

        yellowDarkA: radixColors.yellowDarkA,
        warningDarkA: {
          warningDarkA1: "var(--yellowDarkA1)",
          warningDarkA2: "var(--yellowDarkA2)",
          warningDarkA3: "var(--yellowDarkA3)",
          warningDarkA4: "var(--yellowDarkA4)",
          warningDarkA5: "var(--yellowDarkA5)",
          warningDarkA6: "var(--yellowDarkA6)",
          warningDarkA7: "var(--yellowDarkA7)",
          warningDarkA8: "var(--yellowDarkA8)",
          warningDarkA9: "var(--yellowDarkA9)",
          warningDarkA10: "var(--yellowDarkA10)",
          warningDarkA11: "var(--yellowDarkA11)",
          warningDarkA12: "var(--yellowDarkA12)",
        },

        blue: radixColors.blue,
        info: {
          info1: "var(--blue1)",
          info2: "var(--blue2)",
          info3: "var(--blue3)",
          info4: "var(--blue4)",
          info5: "var(--blue5)",
          info6: "var(--blue6)",
          info7: "var(--blue7)",
          info8: "var(--blue8)",
          info9: "var(--blue9)",
          info10: "var(--blue10)",
          info11: "var(--blue11)",
          info12: "var(--blue12)",
        },

        blueA: radixColors.blueA,
        infoA: {
          infoA1: "var(--blueA1)",
          infoA2: "var(--blueA2)",
          infoA3: "var(--blueA3)",
          infoA4: "var(--blueA4)",
          infoA5: "var(--blueA5)",
          infoA6: "var(--blueA6)",
          infoA7: "var(--blueA7)",
          infoA8: "var(--blueA8)",
          infoA9: "var(--blueA9)",
          infoA10: "var(--blueA10)",
          infoA11: "var(--blueA11)",
          infoA12: "var(--blueA12)",
        },

        blueDark: radixColors.blueDark,
        infoDark: {
          infoDark1: "var(--blueDark1)",
          infoDark2: "var(--blueDark2)",
          infoDark3: "var(--blueDark3)",
          infoDark4: "var(--blueDark4)",
          infoDark5: "var(--blueDark5)",
          infoDark6: "var(--blueDark6)",
          infoDark7: "var(--blueDark7)",
          infoDark8: "var(--blueDark8)",
          infoDark9: "var(--blueDark9)",
          infoDark10: "var(--blueDark10)",
        },

        blueDarkA: radixColors.blueDarkA,
        infoDarkA: {
          infoDarkA1: "var(--blueDarkA1)",
          infoDarkA2: "var(--blueDarkA2)",
          infoDarkA3: "var(--blueDarkA3)",
          infoDarkA4: "var(--blueDarkA4)",
          infoDarkA5: "var(--blueDarkA5)",
          infoDarkA6: "var(--blueDarkA6)",
          infoDarkA7: "var(--blueDarkA7)",
          infoDarkA8: "var(--blueDarkA8)",
          infoDarkA9: "var(--blueDarkA9)",
          infoDarkA10: "var(--blueDarkA10)",
          infoDarkA11: "var(--blueDarkA11)",
          infoDarkA12: "var(--blueDarkA12)",
        },
      },
    }),
  ],
};

// Radix Colors Scale

// 1 App background
// 2 Subtle background

// 3 UI element background
// 4 Hovered UI element background
// 5 Active / Selected UI element background

// 6 Subtle borders and separators
// 7 UI element border and focus rings
// 8 Hovered UI element border

// 9 Solid backgrounds
// 10 Hovered solid backgrounds

// 11 Low-contrast text
// 12 High-contrast text
